//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int CarId { get; set; }
        public int Amount { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public int CassierId { get; set; }
        public Nullable<int> DeliveryId { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual User User { get; set; }
    }
}
